list_1 = [1,2,3,4,5]
print("after adding element in list")
list_1.append(6)
print(list_1)
print("after inserting element in list")
list_1.insert(1,7)
print(list_1)
print("after removing element from list")
list_1.remove(7)
print(list_1)
print("after pop element")
list_1.pop()
print(list_1)
print("after sorting element in list")
list_1.sort()
print(list_1)
print("after reverse element in list")
list_1.reverse()
print(list_1)