list1 = [5,-3,12,0,-7,8]
print("The length of list is :",len(list1))
Sum = sum(list1)
print("Sum of all elements in a list :",Sum)
Max = max(list1)
print("Maximum value of list :",Max)
Min = min(list1)
print("Minimum value of list :",Min)
SortAsc = sorted(list1)
print("Ascending order of list :",SortAsc)
# SortDsc = sorted(dsc.list1)
# print(SortDsc)